// This file is automatically generated by qtc from "integration.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line testdata/templates/integration.qtpl:1
package templates

//line testdata/templates/integration.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// This is a template for integration test.
// It should contains all the quicktemplate stuff.
//

//line testdata/templates/integration.qtpl:4
import "fmt"

//line testdata/templates/integration.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line testdata/templates/integration.qtpl:6
func StreamIntegration(qw422016 *qt422016.Writer) {
	//line testdata/templates/integration.qtpl:6
	qw422016.N().S(`
	Output tags`)
	//line testdata/templates/integration.qtpl:6
	qw422016.N().S("`")
	//line testdata/templates/integration.qtpl:6
	qw422016.N().S(` verification.

	`)
	//line testdata/templates/integration.qtpl:10
	p := &integrationPage{
		S: "foobar",
	}

	//line testdata/templates/integration.qtpl:13
	qw422016.N().S(`
	Embedded func template: `)
	//line testdata/templates/integration.qtpl:14
	streamembeddedFunc(qw422016, p)
	//line testdata/templates/integration.qtpl:14
	qw422016.N().S(`

	Html-escaped output tags:
	<ul>
		<li>`)
	//line testdata/templates/integration.qtpl:18
	qw422016.E().S("<b>html-escaped `string</b>")
	//line testdata/templates/integration.qtpl:18
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:19
	qw422016.E().Z([]byte("<b>html-escaped `byte slice</b>"))
	//line testdata/templates/integration.qtpl:19
	qw422016.N().S(`</li>
		<li>Int: `)
	//line testdata/templates/integration.qtpl:20
	qw422016.N().D(42)
	//line testdata/templates/integration.qtpl:20
	qw422016.N().S(`</li>
		<li>Float: `)
	//line testdata/templates/integration.qtpl:21
	qw422016.N().F(3.14)
	//line testdata/templates/integration.qtpl:21
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:22
	qw422016.E().Q(`<quoted> "json"
				string`)
	//line testdata/templates/integration.qtpl:23
	qw422016.N().S(`</li>
		<li>alert("foo `)
	//line testdata/templates/integration.qtpl:24
	qw422016.E().J(`"json"-safe
				<string>`)
	//line testdata/templates/integration.qtpl:25
	qw422016.N().S(` aa")</li>
		<li><a href="?`)
	//line testdata/templates/integration.qtpl:26
	qw422016.N().U("ключ")
	//line testdata/templates/integration.qtpl:26
	qw422016.N().S(`=`)
	//line testdata/templates/integration.qtpl:26
	qw422016.N().U("значение&=?123")
	//line testdata/templates/integration.qtpl:26
	qw422016.N().S(`">test</a></li>
		<li>`)
	//line testdata/templates/integration.qtpl:27
	qw422016.E().V(struct{ A string }{A: "<b>foobar`</b>"})
	//line testdata/templates/integration.qtpl:27
	qw422016.N().S(`</li>
	</ul>

	Output tags without html escaping
	<ul>
		<li>`)
	//line testdata/templates/integration.qtpl:32
	qw422016.N().S("<b>html-escaped `string</b>")
	//line testdata/templates/integration.qtpl:32
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:33
	qw422016.N().Z([]byte("<b>html-escaped `byte slice</b>"))
	//line testdata/templates/integration.qtpl:33
	qw422016.N().S(`</li>
		<li>Int: `)
	//line testdata/templates/integration.qtpl:34
	qw422016.N().D(42)
	//line testdata/templates/integration.qtpl:34
	qw422016.N().S(`</li>
		<li>Float: `)
	//line testdata/templates/integration.qtpl:35
	qw422016.N().F(3.14)
	//line testdata/templates/integration.qtpl:35
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:36
	qw422016.N().Q(`<quoted> "json"
				string`)
	//line testdata/templates/integration.qtpl:37
	qw422016.N().S(`</li>
		<li>alert("foo `)
	//line testdata/templates/integration.qtpl:38
	qw422016.N().J(`"json"-safe
				<string>`)
	//line testdata/templates/integration.qtpl:39
	qw422016.N().S(` aa")</li>
		<li><a href="?`)
	//line testdata/templates/integration.qtpl:40
	qw422016.N().U("ключ")
	//line testdata/templates/integration.qtpl:40
	qw422016.N().S(`=`)
	//line testdata/templates/integration.qtpl:40
	qw422016.N().U("значение&=?123")
	//line testdata/templates/integration.qtpl:40
	qw422016.N().S(`">test</a></li>
		<li>`)
	//line testdata/templates/integration.qtpl:41
	qw422016.N().V(struct{ A string }{A: "<b>foobar`</b>"})
	//line testdata/templates/integration.qtpl:41
	qw422016.N().S(`</li>
	</ul>

	`)
	//line testdata/templates/integration.qtpl:44
	qw422016.N().S(`Strip space`)
	//line testdata/templates/integration.qtpl:45
	qw422016.N().S(` `)
	//line testdata/templates/integration.qtpl:45
	qw422016.N().S(`between lines and tags`)
	//line testdata/templates/integration.qtpl:47
	qw422016.N().S(`
			Tags aren't parsed {%inside %}
			plain
		`)
	//line testdata/templates/integration.qtpl:51
	// one-liner comment

	//line testdata/templates/integration.qtpl:53
	// multi-line
	// comment

	//line testdata/templates/integration.qtpl:57
	/*
	  yet another
	  multi-line comment
	*/

	//line testdata/templates/integration.qtpl:62
	qw422016.N().S(`

	`)
	//line testdata/templates/integration.qtpl:64
	qw422016.N().S(`Collapse space `)
	//line testdata/templates/integration.qtpl:65
	qw422016.N().S(` `)
	//line testdata/templates/integration.qtpl:65
	qw422016.N().S(`between `)
	//line testdata/templates/integration.qtpl:66
	qw422016.N().S(`
`)
	//line testdata/templates/integration.qtpl:66
	qw422016.N().S(`lines and tags `)
	//line testdata/templates/integration.qtpl:72
	for _, s := range []string{"foo", "bar", "baz"} {
		//line testdata/templates/integration.qtpl:73
		if s == "bar" {
			//line testdata/templates/integration.qtpl:73
			qw422016.N().S(`Bar `)
			//line testdata/templates/integration.qtpl:75
		} else if s == "baz" {
			//line testdata/templates/integration.qtpl:75
			qw422016.N().S(`Baz `)
			//line testdata/templates/integration.qtpl:77
			break
			//line testdata/templates/integration.qtpl:78
		} else {
			//line testdata/templates/integration.qtpl:79
			if s == "never" {
				//line testdata/templates/integration.qtpl:80
				return
				//line testdata/templates/integration.qtpl:81
			}
			//line testdata/templates/integration.qtpl:81
			qw422016.N().S(`s = `)
			//line testdata/templates/integration.qtpl:82
			qw422016.E().S(s)
			//line testdata/templates/integration.qtpl:83
			continue
			//line testdata/templates/integration.qtpl:84
		}
		//line testdata/templates/integration.qtpl:85
	}
	//line testdata/templates/integration.qtpl:86
	qw422016.N().S(`

	tail of the func
`)
//line testdata/templates/integration.qtpl:89
}

//line testdata/templates/integration.qtpl:89
func WriteIntegration(qq422016 qtio422016.Writer) {
	//line testdata/templates/integration.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:89
	StreamIntegration(qw422016)
	//line testdata/templates/integration.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:89
}

//line testdata/templates/integration.qtpl:89
func Integration() string {
	//line testdata/templates/integration.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:89
	WriteIntegration(qb422016)
	//line testdata/templates/integration.qtpl:89
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:89
	return qs422016
//line testdata/templates/integration.qtpl:89
}

//line testdata/templates/integration.qtpl:92
type Page interface {
	//line testdata/templates/integration.qtpl:92
	Header() string
	//line testdata/templates/integration.qtpl:92
	StreamHeader(qw422016 *qt422016.Writer)
	//line testdata/templates/integration.qtpl:92
	WriteHeader(qq422016 qtio422016.Writer)
	//line testdata/templates/integration.qtpl:92
	Body() string
	//line testdata/templates/integration.qtpl:92
	StreamBody(qw422016 *qt422016.Writer)
	//line testdata/templates/integration.qtpl:92
	WriteBody(qq422016 qtio422016.Writer)
//line testdata/templates/integration.qtpl:92
}

//line testdata/templates/integration.qtpl:98
func streamembeddedFunc(qw422016 *qt422016.Writer, p Page) {
	//line testdata/templates/integration.qtpl:98
	qw422016.N().S(`
	Page's header: `)
	//line testdata/templates/integration.qtpl:99
	p.StreamHeader(qw422016)
	//line testdata/templates/integration.qtpl:99
	qw422016.N().S(`
	Body: `)
	//line testdata/templates/integration.qtpl:100
	qw422016.N().S(fmt.Sprintf("<b>%s</b>", p.Body()))
	//line testdata/templates/integration.qtpl:100
	qw422016.N().S(`
`)
//line testdata/templates/integration.qtpl:101
}

//line testdata/templates/integration.qtpl:101
func writeembeddedFunc(qq422016 qtio422016.Writer, p Page) {
	//line testdata/templates/integration.qtpl:101
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:101
	streamembeddedFunc(qw422016, p)
	//line testdata/templates/integration.qtpl:101
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:101
}

//line testdata/templates/integration.qtpl:101
func embeddedFunc(p Page) string {
	//line testdata/templates/integration.qtpl:101
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:101
	writeembeddedFunc(qb422016, p)
	//line testdata/templates/integration.qtpl:101
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:101
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:101
	return qs422016
//line testdata/templates/integration.qtpl:101
}

//line testdata/templates/integration.qtpl:104
type integrationPage struct {
	S string
}

//line testdata/templates/integration.qtpl:109
func (p *integrationPage) StreamHeader(qw422016 *qt422016.Writer) {
//line testdata/templates/integration.qtpl:109
qw422016.N().S(`Header`) }

//line testdata/templates/integration.qtpl:109
//line testdata/templates/integration.qtpl:109
func (p *integrationPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line testdata/templates/integration.qtpl:109
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:109
	p.StreamHeader(qw422016)
	//line testdata/templates/integration.qtpl:109
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:109
}

//line testdata/templates/integration.qtpl:109
func (p *integrationPage) Header() string {
	//line testdata/templates/integration.qtpl:109
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:109
	p.WriteHeader(qb422016)
	//line testdata/templates/integration.qtpl:109
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:109
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:109
	return qs422016
//line testdata/templates/integration.qtpl:109
}

//line testdata/templates/integration.qtpl:111
func (p *integrationPage) StreamBody(qw422016 *qt422016.Writer) {
	//line testdata/templates/integration.qtpl:111
	qw422016.N().S(`
	S=`)
	//line testdata/templates/integration.qtpl:112
	qw422016.E().Q(p.S)
	//line testdata/templates/integration.qtpl:112
	qw422016.N().S(`
`)
//line testdata/templates/integration.qtpl:113
}

//line testdata/templates/integration.qtpl:113
func (p *integrationPage) WriteBody(qq422016 qtio422016.Writer) {
	//line testdata/templates/integration.qtpl:113
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:113
	p.StreamBody(qw422016)
	//line testdata/templates/integration.qtpl:113
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:113
}

//line testdata/templates/integration.qtpl:113
func (p *integrationPage) Body() string {
	//line testdata/templates/integration.qtpl:113
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:113
	p.WriteBody(qb422016)
	//line testdata/templates/integration.qtpl:113
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:113
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:113
	return qs422016
//line testdata/templates/integration.qtpl:113
}
