// This file is automatically generated by qtc from "integration.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line testdata/templates/integration.qtpl:1
package templates

//line testdata/templates/integration.qtpl:1
import (
	"io"

	"github.com/valyala/quicktemplate"
)

// This is a template for integration test.
// It should contains all the quicktemplate stuff.
//

//line testdata/templates/integration.qtpl:4
var (
	_ = io.Copy
	_ = quicktemplate.AcquireByteBuffer
)

//line testdata/templates/integration.qtpl:4
func StreamIntegration(qw *quicktemplate.Writer) {
	//line testdata/templates/integration.qtpl:4
	qw.N().S(`
	Output tags`)
	//line testdata/templates/integration.qtpl:4
	qw.N().S("`")
	//line testdata/templates/integration.qtpl:4
	qw.N().S(` verification.

	`)
	//line testdata/templates/integration.qtpl:8
	p := &integrationPage{
		S: "foobar",
	}

	//line testdata/templates/integration.qtpl:11
	qw.N().S(`
	Embedded func template: `)
	//line testdata/templates/integration.qtpl:12
	streamembeddedFunc(qw, p)
	//line testdata/templates/integration.qtpl:12
	qw.N().S(`

	Html-escaped output tags:
	<ul>
		<li>`)
	//line testdata/templates/integration.qtpl:16
	qw.E().S("<b>html-escaped `string</b>")
	//line testdata/templates/integration.qtpl:16
	qw.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:17
	qw.E().Z([]byte("<b>html-escaped `byte slice</b>"))
	//line testdata/templates/integration.qtpl:17
	qw.N().S(`</li>
		<li>Int: `)
	//line testdata/templates/integration.qtpl:18
	qw.N().D(42)
	//line testdata/templates/integration.qtpl:18
	qw.N().S(`</li>
		<li>Float: `)
	//line testdata/templates/integration.qtpl:19
	qw.N().F(3.14)
	//line testdata/templates/integration.qtpl:19
	qw.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:20
	qw.E().Q(`<quoted> "json"
				string`)
	//line testdata/templates/integration.qtpl:21
	qw.N().S(`</li>
		<li>alert("foo `)
	//line testdata/templates/integration.qtpl:22
	qw.E().J(`"json"-safe
				<string>`)
	//line testdata/templates/integration.qtpl:23
	qw.N().S(` aa")</li>
		<li>`)
	//line testdata/templates/integration.qtpl:24
	qw.E().V(struct{ A string }{A: "<b>foobar`</b>"})
	//line testdata/templates/integration.qtpl:24
	qw.N().S(`</li>
	</ul>

	Output tags without html escaping
	<ul>
		<li>`)
	//line testdata/templates/integration.qtpl:29
	qw.N().S("<b>html-escaped `string</b>")
	//line testdata/templates/integration.qtpl:29
	qw.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:30
	qw.N().Z([]byte("<b>html-escaped `byte slice</b>"))
	//line testdata/templates/integration.qtpl:30
	qw.N().S(`</li>
		<li>Int: `)
	//line testdata/templates/integration.qtpl:31
	qw.N().D(42)
	//line testdata/templates/integration.qtpl:31
	qw.N().S(`</li>
		<li>Float: `)
	//line testdata/templates/integration.qtpl:32
	qw.N().F(3.14)
	//line testdata/templates/integration.qtpl:32
	qw.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:33
	qw.N().Q(`<quoted> "json"
				string`)
	//line testdata/templates/integration.qtpl:34
	qw.N().S(`</li>
		<li>alert("foo `)
	//line testdata/templates/integration.qtpl:35
	qw.N().J(`"json"-safe
				<string>`)
	//line testdata/templates/integration.qtpl:36
	qw.N().S(` aa")</li>
		<li>`)
	//line testdata/templates/integration.qtpl:37
	qw.N().V(struct{ A string }{A: "<b>foobar`</b>"})
	//line testdata/templates/integration.qtpl:37
	qw.N().S(`</li>
	</ul>

	`)
	//line testdata/templates/integration.qtpl:40
	qw.N().S(`Strip space`)
	//line testdata/templates/integration.qtpl:41
	qw.N().S(` `)
	//line testdata/templates/integration.qtpl:41
	qw.N().S(`between lines and tags`)
	//line testdata/templates/integration.qtpl:43
	qw.N().S(`
			Tags aren't parsed {%inside %}
			plain
		`)
	//line testdata/templates/integration.qtpl:47
	qw.N().S(`

	`)
	//line testdata/templates/integration.qtpl:49
	qw.N().S(`Collapse space`)
	//line testdata/templates/integration.qtpl:50
	qw.N().S(` `)
	//line testdata/templates/integration.qtpl:50
	qw.N().S(`between`)
	//line testdata/templates/integration.qtpl:51
	qw.N().S(`
`)
	//line testdata/templates/integration.qtpl:51
	qw.N().S(`lines and tags`)
	//line testdata/templates/integration.qtpl:57
	for _, s := range []string{"foo", "bar", "baz"} {
		//line testdata/templates/integration.qtpl:58
		if s == "bar" {
			//line testdata/templates/integration.qtpl:58
			qw.N().S(`Bar`)
			//line testdata/templates/integration.qtpl:60
		} else if s == "baz" {
			//line testdata/templates/integration.qtpl:60
			qw.N().S(`Baz`)
			//line testdata/templates/integration.qtpl:62
			break
			//line testdata/templates/integration.qtpl:63
		} else {
			//line testdata/templates/integration.qtpl:64
			if s == "never" {
				//line testdata/templates/integration.qtpl:65
				return
				//line testdata/templates/integration.qtpl:66
			}
			//line testdata/templates/integration.qtpl:66
			qw.N().S(`s =`)
			//line testdata/templates/integration.qtpl:67
			qw.E().S(s)
			//line testdata/templates/integration.qtpl:68
		}
		//line testdata/templates/integration.qtpl:69
	}
	//line testdata/templates/integration.qtpl:70
	qw.N().S(`

	tail of the func
`)
//line testdata/templates/integration.qtpl:73
}

//line testdata/templates/integration.qtpl:73
func WriteIntegration(qww io.Writer) {
	//line testdata/templates/integration.qtpl:73
	qw := quicktemplate.AcquireWriter(qww)
	//line testdata/templates/integration.qtpl:73
	StreamIntegration(qw)
	//line testdata/templates/integration.qtpl:73
	quicktemplate.ReleaseWriter(qw)
//line testdata/templates/integration.qtpl:73
}

//line testdata/templates/integration.qtpl:73
func Integration() string {
	//line testdata/templates/integration.qtpl:73
	qb := quicktemplate.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:73
	WriteIntegration(qb)
	//line testdata/templates/integration.qtpl:73
	qs := string(qb.B)
	//line testdata/templates/integration.qtpl:73
	quicktemplate.ReleaseByteBuffer(qb)
	//line testdata/templates/integration.qtpl:73
	return qs
//line testdata/templates/integration.qtpl:73
}

//line testdata/templates/integration.qtpl:76
type Page interface {
	//line testdata/templates/integration.qtpl:76
	Header() string
	//line testdata/templates/integration.qtpl:76
	StreamHeader(qw *quicktemplate.Writer)
	//line testdata/templates/integration.qtpl:76
	WriteHeader(qww io.Writer)
	//line testdata/templates/integration.qtpl:76
	Body() string
	//line testdata/templates/integration.qtpl:76
	StreamBody(qw *quicktemplate.Writer)
	//line testdata/templates/integration.qtpl:76
	WriteBody(qww io.Writer)
//line testdata/templates/integration.qtpl:76
}

//line testdata/templates/integration.qtpl:82
func streamembeddedFunc(qw *quicktemplate.Writer, p Page) {
	//line testdata/templates/integration.qtpl:82
	qw.N().S(`
	Page's header: `)
	//line testdata/templates/integration.qtpl:83
	p.StreamHeader(qw)
	//line testdata/templates/integration.qtpl:83
	qw.N().S(`
	Body: `)
	//line testdata/templates/integration.qtpl:84
	qw.N().S(p.Body())
	//line testdata/templates/integration.qtpl:84
	qw.N().S(`
`)
//line testdata/templates/integration.qtpl:85
}

//line testdata/templates/integration.qtpl:85
func writeembeddedFunc(qww io.Writer, p Page) {
	//line testdata/templates/integration.qtpl:85
	qw := quicktemplate.AcquireWriter(qww)
	//line testdata/templates/integration.qtpl:85
	streamembeddedFunc(qw, p)
	//line testdata/templates/integration.qtpl:85
	quicktemplate.ReleaseWriter(qw)
//line testdata/templates/integration.qtpl:85
}

//line testdata/templates/integration.qtpl:85
func embeddedFunc(p Page) string {
	//line testdata/templates/integration.qtpl:85
	qb := quicktemplate.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:85
	writeembeddedFunc(qb, p)
	//line testdata/templates/integration.qtpl:85
	qs := string(qb.B)
	//line testdata/templates/integration.qtpl:85
	quicktemplate.ReleaseByteBuffer(qb)
	//line testdata/templates/integration.qtpl:85
	return qs
//line testdata/templates/integration.qtpl:85
}

//line testdata/templates/integration.qtpl:88
type integrationPage struct {
	S string
}

//line testdata/templates/integration.qtpl:93
func (p *integrationPage) StreamHeader(qw *quicktemplate.Writer) {
//line testdata/templates/integration.qtpl:93
qw.N().S(`Header`) }

//line testdata/templates/integration.qtpl:93
//line testdata/templates/integration.qtpl:93
func (p *integrationPage) WriteHeader(qww io.Writer) {
	//line testdata/templates/integration.qtpl:93
	qw := quicktemplate.AcquireWriter(qww)
	//line testdata/templates/integration.qtpl:93
	p.StreamHeader(qw)
	//line testdata/templates/integration.qtpl:93
	quicktemplate.ReleaseWriter(qw)
//line testdata/templates/integration.qtpl:93
}

//line testdata/templates/integration.qtpl:93
func (p *integrationPage) Header() string {
	//line testdata/templates/integration.qtpl:93
	qb := quicktemplate.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:93
	p.WriteHeader(qb)
	//line testdata/templates/integration.qtpl:93
	qs := string(qb.B)
	//line testdata/templates/integration.qtpl:93
	quicktemplate.ReleaseByteBuffer(qb)
	//line testdata/templates/integration.qtpl:93
	return qs
//line testdata/templates/integration.qtpl:93
}

//line testdata/templates/integration.qtpl:95
func (p *integrationPage) StreamBody(qw *quicktemplate.Writer) {
	//line testdata/templates/integration.qtpl:95
	qw.N().S(`
	S=`)
	//line testdata/templates/integration.qtpl:96
	qw.E().Q(p.S)
	//line testdata/templates/integration.qtpl:96
	qw.N().S(`
`)
//line testdata/templates/integration.qtpl:97
}

//line testdata/templates/integration.qtpl:97
func (p *integrationPage) WriteBody(qww io.Writer) {
	//line testdata/templates/integration.qtpl:97
	qw := quicktemplate.AcquireWriter(qww)
	//line testdata/templates/integration.qtpl:97
	p.StreamBody(qw)
	//line testdata/templates/integration.qtpl:97
	quicktemplate.ReleaseWriter(qw)
//line testdata/templates/integration.qtpl:97
}

//line testdata/templates/integration.qtpl:97
func (p *integrationPage) Body() string {
	//line testdata/templates/integration.qtpl:97
	qb := quicktemplate.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:97
	p.WriteBody(qb)
	//line testdata/templates/integration.qtpl:97
	qs := string(qb.B)
	//line testdata/templates/integration.qtpl:97
	quicktemplate.ReleaseByteBuffer(qb)
	//line testdata/templates/integration.qtpl:97
	return qs
//line testdata/templates/integration.qtpl:97
}
