// This file is automatically generated by qtc from "integration.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line testdata/templates/integration.qtpl:1
package templates

//line testdata/templates/integration.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// This is a template for integration test.
// It should contains all the quicktemplate stuff.
//

//line testdata/templates/integration.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line testdata/templates/integration.qtpl:4
func StreamIntegration(qw422016 *qt422016.Writer) {
	//line testdata/templates/integration.qtpl:4
	qw422016.N().S(`
	Output tags`)
	//line testdata/templates/integration.qtpl:4
	qw422016.N().S("`")
	//line testdata/templates/integration.qtpl:4
	qw422016.N().S(` verification.

	`)
	//line testdata/templates/integration.qtpl:8
	p := &integrationPage{
		S: "foobar",
	}

	//line testdata/templates/integration.qtpl:11
	qw422016.N().S(`
	Embedded func template: `)
	//line testdata/templates/integration.qtpl:12
	streamembeddedFunc(qw422016, p)
	//line testdata/templates/integration.qtpl:12
	qw422016.N().S(`

	Html-escaped output tags:
	<ul>
		<li>`)
	//line testdata/templates/integration.qtpl:16
	qw422016.E().S("<b>html-escaped `string</b>")
	//line testdata/templates/integration.qtpl:16
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:17
	qw422016.E().Z([]byte("<b>html-escaped `byte slice</b>"))
	//line testdata/templates/integration.qtpl:17
	qw422016.N().S(`</li>
		<li>Int: `)
	//line testdata/templates/integration.qtpl:18
	qw422016.N().D(42)
	//line testdata/templates/integration.qtpl:18
	qw422016.N().S(`</li>
		<li>Float: `)
	//line testdata/templates/integration.qtpl:19
	qw422016.N().F(3.14)
	//line testdata/templates/integration.qtpl:19
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:20
	qw422016.E().Q(`<quoted> "json"
				string`)
	//line testdata/templates/integration.qtpl:21
	qw422016.N().S(`</li>
		<li>alert("foo `)
	//line testdata/templates/integration.qtpl:22
	qw422016.E().J(`"json"-safe
				<string>`)
	//line testdata/templates/integration.qtpl:23
	qw422016.N().S(` aa")</li>
		<li><a href="?`)
	//line testdata/templates/integration.qtpl:24
	qw422016.N().U("ключ")
	//line testdata/templates/integration.qtpl:24
	qw422016.N().S(`=`)
	//line testdata/templates/integration.qtpl:24
	qw422016.N().U("значение&=?123")
	//line testdata/templates/integration.qtpl:24
	qw422016.N().S(`">test</a></li>
		<li>`)
	//line testdata/templates/integration.qtpl:25
	qw422016.E().V(struct{ A string }{A: "<b>foobar`</b>"})
	//line testdata/templates/integration.qtpl:25
	qw422016.N().S(`</li>
	</ul>

	Output tags without html escaping
	<ul>
		<li>`)
	//line testdata/templates/integration.qtpl:30
	qw422016.N().S("<b>html-escaped `string</b>")
	//line testdata/templates/integration.qtpl:30
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:31
	qw422016.N().Z([]byte("<b>html-escaped `byte slice</b>"))
	//line testdata/templates/integration.qtpl:31
	qw422016.N().S(`</li>
		<li>Int: `)
	//line testdata/templates/integration.qtpl:32
	qw422016.N().D(42)
	//line testdata/templates/integration.qtpl:32
	qw422016.N().S(`</li>
		<li>Float: `)
	//line testdata/templates/integration.qtpl:33
	qw422016.N().F(3.14)
	//line testdata/templates/integration.qtpl:33
	qw422016.N().S(`</li>
		<li>`)
	//line testdata/templates/integration.qtpl:34
	qw422016.N().Q(`<quoted> "json"
				string`)
	//line testdata/templates/integration.qtpl:35
	qw422016.N().S(`</li>
		<li>alert("foo `)
	//line testdata/templates/integration.qtpl:36
	qw422016.N().J(`"json"-safe
				<string>`)
	//line testdata/templates/integration.qtpl:37
	qw422016.N().S(` aa")</li>
		<li><a href="?`)
	//line testdata/templates/integration.qtpl:38
	qw422016.N().U("ключ")
	//line testdata/templates/integration.qtpl:38
	qw422016.N().S(`=`)
	//line testdata/templates/integration.qtpl:38
	qw422016.N().U("значение&=?123")
	//line testdata/templates/integration.qtpl:38
	qw422016.N().S(`">test</a></li>
		<li>`)
	//line testdata/templates/integration.qtpl:39
	qw422016.N().V(struct{ A string }{A: "<b>foobar`</b>"})
	//line testdata/templates/integration.qtpl:39
	qw422016.N().S(`</li>
	</ul>

	`)
	//line testdata/templates/integration.qtpl:42
	qw422016.N().S(`Strip space`)
	//line testdata/templates/integration.qtpl:43
	qw422016.N().S(` `)
	//line testdata/templates/integration.qtpl:43
	qw422016.N().S(`between lines and tags`)
	//line testdata/templates/integration.qtpl:45
	qw422016.N().S(`
			Tags aren't parsed {%inside %}
			plain
		`)
	//line testdata/templates/integration.qtpl:49
	qw422016.N().S(`

	`)
	//line testdata/templates/integration.qtpl:51
	qw422016.N().S(`Collapse space `)
	//line testdata/templates/integration.qtpl:52
	qw422016.N().S(` `)
	//line testdata/templates/integration.qtpl:52
	qw422016.N().S(`between `)
	//line testdata/templates/integration.qtpl:53
	qw422016.N().S(`
`)
	//line testdata/templates/integration.qtpl:53
	qw422016.N().S(`lines and tags `)
	//line testdata/templates/integration.qtpl:59
	for _, s := range []string{"foo", "bar", "baz"} {
		//line testdata/templates/integration.qtpl:60
		if s == "bar" {
			//line testdata/templates/integration.qtpl:60
			qw422016.N().S(`Bar `)
			//line testdata/templates/integration.qtpl:62
		} else if s == "baz" {
			//line testdata/templates/integration.qtpl:62
			qw422016.N().S(`Baz `)
			//line testdata/templates/integration.qtpl:64
			break
			//line testdata/templates/integration.qtpl:65
		} else {
			//line testdata/templates/integration.qtpl:66
			if s == "never" {
				//line testdata/templates/integration.qtpl:67
				return
				//line testdata/templates/integration.qtpl:68
			}
			//line testdata/templates/integration.qtpl:68
			qw422016.N().S(`s = `)
			//line testdata/templates/integration.qtpl:69
			qw422016.E().S(s)
			//line testdata/templates/integration.qtpl:70
		}
		//line testdata/templates/integration.qtpl:71
	}
	//line testdata/templates/integration.qtpl:72
	qw422016.N().S(`

	tail of the func
`)
//line testdata/templates/integration.qtpl:75
}

//line testdata/templates/integration.qtpl:75
func WriteIntegration(qq422016 qtio422016.Writer) {
	//line testdata/templates/integration.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:75
	StreamIntegration(qw422016)
	//line testdata/templates/integration.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:75
}

//line testdata/templates/integration.qtpl:75
func Integration() string {
	//line testdata/templates/integration.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:75
	WriteIntegration(qb422016)
	//line testdata/templates/integration.qtpl:75
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:75
	return qs422016
//line testdata/templates/integration.qtpl:75
}

//line testdata/templates/integration.qtpl:78
type Page interface {
	//line testdata/templates/integration.qtpl:78
	Header() string
	//line testdata/templates/integration.qtpl:78
	StreamHeader(qw422016 *qt422016.Writer)
	//line testdata/templates/integration.qtpl:78
	WriteHeader(qq422016 qtio422016.Writer)
	//line testdata/templates/integration.qtpl:78
	Body() string
	//line testdata/templates/integration.qtpl:78
	StreamBody(qw422016 *qt422016.Writer)
	//line testdata/templates/integration.qtpl:78
	WriteBody(qq422016 qtio422016.Writer)
//line testdata/templates/integration.qtpl:78
}

//line testdata/templates/integration.qtpl:84
func streamembeddedFunc(qw422016 *qt422016.Writer, p Page) {
	//line testdata/templates/integration.qtpl:84
	qw422016.N().S(`
	Page's header: `)
	//line testdata/templates/integration.qtpl:85
	p.StreamHeader(qw422016)
	//line testdata/templates/integration.qtpl:85
	qw422016.N().S(`
	Body: `)
	//line testdata/templates/integration.qtpl:86
	qw422016.N().S(p.Body())
	//line testdata/templates/integration.qtpl:86
	qw422016.N().S(`
`)
//line testdata/templates/integration.qtpl:87
}

//line testdata/templates/integration.qtpl:87
func writeembeddedFunc(qq422016 qtio422016.Writer, p Page) {
	//line testdata/templates/integration.qtpl:87
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:87
	streamembeddedFunc(qw422016, p)
	//line testdata/templates/integration.qtpl:87
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:87
}

//line testdata/templates/integration.qtpl:87
func embeddedFunc(p Page) string {
	//line testdata/templates/integration.qtpl:87
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:87
	writeembeddedFunc(qb422016, p)
	//line testdata/templates/integration.qtpl:87
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:87
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:87
	return qs422016
//line testdata/templates/integration.qtpl:87
}

//line testdata/templates/integration.qtpl:90
type integrationPage struct {
	S string
}

//line testdata/templates/integration.qtpl:95
func (p *integrationPage) StreamHeader(qw422016 *qt422016.Writer) {
//line testdata/templates/integration.qtpl:95
qw422016.N().S(`Header`) }

//line testdata/templates/integration.qtpl:95
//line testdata/templates/integration.qtpl:95
func (p *integrationPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line testdata/templates/integration.qtpl:95
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:95
	p.StreamHeader(qw422016)
	//line testdata/templates/integration.qtpl:95
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:95
}

//line testdata/templates/integration.qtpl:95
func (p *integrationPage) Header() string {
	//line testdata/templates/integration.qtpl:95
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:95
	p.WriteHeader(qb422016)
	//line testdata/templates/integration.qtpl:95
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:95
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:95
	return qs422016
//line testdata/templates/integration.qtpl:95
}

//line testdata/templates/integration.qtpl:97
func (p *integrationPage) StreamBody(qw422016 *qt422016.Writer) {
	//line testdata/templates/integration.qtpl:97
	qw422016.N().S(`
	S=`)
	//line testdata/templates/integration.qtpl:98
	qw422016.E().Q(p.S)
	//line testdata/templates/integration.qtpl:98
	qw422016.N().S(`
`)
//line testdata/templates/integration.qtpl:99
}

//line testdata/templates/integration.qtpl:99
func (p *integrationPage) WriteBody(qq422016 qtio422016.Writer) {
	//line testdata/templates/integration.qtpl:99
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line testdata/templates/integration.qtpl:99
	p.StreamBody(qw422016)
	//line testdata/templates/integration.qtpl:99
	qt422016.ReleaseWriter(qw422016)
//line testdata/templates/integration.qtpl:99
}

//line testdata/templates/integration.qtpl:99
func (p *integrationPage) Body() string {
	//line testdata/templates/integration.qtpl:99
	qb422016 := qt422016.AcquireByteBuffer()
	//line testdata/templates/integration.qtpl:99
	p.WriteBody(qb422016)
	//line testdata/templates/integration.qtpl:99
	qs422016 := string(qb422016.B)
	//line testdata/templates/integration.qtpl:99
	qt422016.ReleaseByteBuffer(qb422016)
	//line testdata/templates/integration.qtpl:99
	return qs422016
//line testdata/templates/integration.qtpl:99
}
