// This file is automatically generated by qtc from "templates/mainpage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/mainpage.qtpl:1
package templates

//line templates/mainpage.qtpl:1
import (
	"io"

	"github.com/valyala/quicktemplate"
)

// Main page template. Implements BasePage methods.
//

//line templates/mainpage.qtpl:3
import "github.com/valyala/fasthttp"

//line templates/mainpage.qtpl:5
var (
	_ = io.Copy
	_ = quicktemplate.AcquireByteBuffer
)

//line templates/mainpage.qtpl:6
type MainPage struct {
	CTX *fasthttp.RequestCtx
}

//line templates/mainpage.qtpl:12
func (p *MainPage) StreamTitle(qw *quicktemplate.Writer) {
	//line templates/mainpage.qtpl:12
	qw.N().S(`
	This is the main page
`)
//line templates/mainpage.qtpl:14
}

//line templates/mainpage.qtpl:14
func (p *MainPage) WriteTitle(qww io.Writer) {
	//line templates/mainpage.qtpl:14
	qw := quicktemplate.AcquireWriter(qww)
	//line templates/mainpage.qtpl:14
	p.StreamTitle(qw)
	//line templates/mainpage.qtpl:14
	quicktemplate.ReleaseWriter(qw)
//line templates/mainpage.qtpl:14
}

//line templates/mainpage.qtpl:14
func (p *MainPage) Title() string {
	//line templates/mainpage.qtpl:14
	qb := quicktemplate.AcquireByteBuffer()
	//line templates/mainpage.qtpl:14
	p.WriteTitle(qb)
	//line templates/mainpage.qtpl:14
	qs := string(qb.B)
	//line templates/mainpage.qtpl:14
	quicktemplate.ReleaseByteBuffer(qb)
	//line templates/mainpage.qtpl:14
	return qs
//line templates/mainpage.qtpl:14
}

//line templates/mainpage.qtpl:17
func (p *MainPage) StreamBody(qw *quicktemplate.Writer) {
	//line templates/mainpage.qtpl:17
	qw.N().S(`
	<h1>Main page</h1>
	<div>
		Click links below:
		<ul>
			<li><a href="/table?rowsCount=42">Table page</a></li>
			<li><a href="/unknown-page">Error page</a></li>
		</ul>
	</div>
	<div>
		Some info about you:<br/>
		IP: <b>`)
	//line templates/mainpage.qtpl:28
	qw.E().S(p.CTX.RemoteIP().String())
	//line templates/mainpage.qtpl:28
	qw.N().S(`</b><br/>
		User-Agent: <b>`)
	//line templates/mainpage.qtpl:29
	qw.E().Z(p.CTX.UserAgent())
	//line templates/mainpage.qtpl:29
	qw.N().S(`</b><br/>
	</div>
`)
//line templates/mainpage.qtpl:31
}

//line templates/mainpage.qtpl:31
func (p *MainPage) WriteBody(qww io.Writer) {
	//line templates/mainpage.qtpl:31
	qw := quicktemplate.AcquireWriter(qww)
	//line templates/mainpage.qtpl:31
	p.StreamBody(qw)
	//line templates/mainpage.qtpl:31
	quicktemplate.ReleaseWriter(qw)
//line templates/mainpage.qtpl:31
}

//line templates/mainpage.qtpl:31
func (p *MainPage) Body() string {
	//line templates/mainpage.qtpl:31
	qb := quicktemplate.AcquireByteBuffer()
	//line templates/mainpage.qtpl:31
	p.WriteBody(qb)
	//line templates/mainpage.qtpl:31
	qs := string(qb.B)
	//line templates/mainpage.qtpl:31
	quicktemplate.ReleaseByteBuffer(qb)
	//line templates/mainpage.qtpl:31
	return qs
//line templates/mainpage.qtpl:31
}
